config/routes.rb
Rails.application.routes.draw do
  resource :session do
    get :logout, on: :member
  end

  resources :events do
    get :show, on: :member
    post :update, on: :member
  end

  resources :subscriptions do
    resources :events, shallow: true do
      resources :tagged_items
    end
    resources :accounts, shallow: true do
      resources :buckets, shallow: true do
        resources :events
      end
      resources :events
      resources :statements
    end
    resources :tags, shallow: true do
      resources :events
    end
  end



  root to: 'subscriptions#index'
  # map.with_options :controller => "subscriptions", :action => "index" do |home|
  #   home.root
  #   home.connect ""
  # end
end

app/models/statement.rb
class Statement < ActiveRecord::Base
  belongs_to :account
  has_many :account_items, :extend => CategorizedItems, :dependent => :nullify

  before_create :initialize_starting_balance
  after_save :associate_account_items_with_self

  scope :pending, ->{ where(:balanced_at => nil) }
  scope :balanced, ->{ where("balanced_at IS NOT NULL") }

  # attr_accessible :occurred_on, :ending_balance, :cleared

  validates_presence_of :occurred_on, :ending_balance

  def ending_balance=(amount)
    if amount.is_a?(Float)
      amount = (amount.to_s.tr(",", "").to_f * 100).round
    elsif amount =~ /[.,]/
      dollars, cents = amount.split(".")
      dollars = dollars.tr(",", "").to_i

      cents = cents[0,2]
      cents << "0" while cents.length < 2
      cents = cents.to_i

      amount = dollars * 100 + cents
    end

    super(amount)
  end

  def balance
    ending_balance
  end

  def balanced?(reload=false)
    unsettled_balance(reload).zero?
  end

  def settled_balance(reload=false)
    @settled_balance = nil if reload
    @settled_balance ||= account_items.to_a.sum(&:amount)
  end

  def unsettled_balance(reload=false)
    @unsettled_balance = nil if reload
    @unsettled_balance ||= starting_balance + settled_balance(reload) - ending_balance
  end

  def cleared=(ids)
    @ids_to_clear = ids
    @already_updated = false
  end

  protected

    def initialize_starting_balance
      self.starting_balance ||= account.statements.balanced.last.try(:ending_balance) || 0
    end

    def associate_account_items_with_self
      return if @already_updated
      @already_updated = true

      account_items.clear

      ids = ActiveRecord::Base.connection.select_values(sanitize_sql([<<-SQL.squish, account_id, ids_to_clear]))
        SELECT ai.id
          FROM account_items ai
         WHERE ai.account_id = ?
           AND ai.id IN (?)
      SQL

      ActiveRecord::Base.connection.update(sanitize_sql([<<-SQL.squish, id, ids]))
        UPDATE account_items
           SET statement_id = ?
         WHERE id IN (?)
      SQL

      account_items.reset

      if @ids_to_clear
        if balanced?(true) && !balanced_at
          update_attribute :balanced_at, Time.now.utc
        elsif !balanced? && balanced_at
          update_attribute :balanced_at, nil
        end
      end
    end

  private

    def sanitize_sql(sql)
      self.class.send(:sanitize_sql, sql)
    end

    def ids_to_clear
      @ids_to_clear || []
    end

end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :find_account, :only => %w(index new create)
  before_action :find_statement, :only => %w(show edit update destroy)

  def index
    @statements = account.statements.balanced
  end

  def new
    @statement = account.statements.build(:ending_balance => account.balance,
      :occurred_on => Date.today)
  end

  def create
    @statement = account.statements.create(statement_params)
    redirect_to(edit_statement_url(@statement))
  end

  def show
  end

  def edit
    @uncleared = account.account_items.uncleared(:with => statement, :include => :event)
  end

  def update
    statement.update(statement_params)
    redirect_to(account)
  end

  def destroy
    statement.destroy
    redirect_to(account)
  end

  protected

  attr_reader :uncleared, :statements
  helper_method :uncleared, :statements

  attr_reader :account, :statement
  helper_method :account, :statement

  def find_account
    @account = Account.find(params[:account_id])
    @subscription = user.subscriptions.find(@account.subscription_id)
  end

  def find_statement
    @statement = Statement.find(params[:id])
    @account = @statement.account
    @subscription = user.subscriptions.find(@account.subscription_id)
  end

  def statement_params
    params.require(:statement)
          .permit(:occurred_on, :ending_balance, cleared: [])
  end
end

app/helpers/statements_helper.rb
module StatementsHelper
  def uncleared_row_class(item)
    classes = [cycle('odd', 'even')]
    classes << "cleared" if item.statement_id
    classes.join(" ")
  end
end

app/views/statements/_subtotal.html.haml
.subtotal
  .settled
    Subtotal:
    %span.subtotal_dollars= format_cents(subtotal)
  .remaining
    Remaining:
    %span.remaining_dollars{:class => statement.unsettled_balance.zero? ? "balanced" : nil}
      = format_cents(statement.unsettled_balance)

app/views/statements/_uncleared.html.haml
%tr{:id => dom_id(uncleared), :class => uncleared_row_class(uncleared)}
  %td.checkbox= check_box_tag "statement[cleared][]", uncleared.id, uncleared.statement_id, :id => dom_id(uncleared, :check), :onclick => "Statements.toggleCleared(#{uncleared.id})"
  %td.date{:onclick => "Statements.clickItem(#{uncleared.id})"}= uncleared.occurred_on.strftime("%Y-%m-%d")
  - if uncleared.event.check_number
    %td.check{:onclick => "Statements.clickItem(#{uncleared.id})"}= "#" + uncleared.event.check_number.to_s
  %td.actor{:onclick => "Statements.clickItem(#{uncleared.id})"}&= uncleared.event.actor_name
  %td.number{:onclick => "Statements.clickItem(#{uncleared.id})"}
    %span{:style => "display: none;", :id => dom_id(uncleared, :amount)}= uncleared.amount
    = format_cents(uncleared.amount.abs)

app/views/statements/edit.html.haml
#data.content
  %h2== Balance your statement

  .statement.edit.form

    = form_for(statement) do |form|

      %table.general
        %tr
          %th.occurred_on Statement date
          %th.starting_balance Starting balance
          %th.ending_balance Ending balance
        %tr
          %td.occurred_on= form.date_select :occurred_on, :size => 10
          %td#starting_balance.starting_balance.number= format_cents(statement.starting_balance)
          %td.ending_balance
            = "$"
            = form.text_field(:ending_balance, :size => 8, :class => "number", :value => format_cents(statement.ending_balance, :unit => ""), :onchange => "Statements.updateBalances()")
        
      - if uncleared.deposits.any?
        %fieldset#deposits
          %legend Deposits

          .uncleared.deposits
            %table= render :partial => "statements/uncleared", :collection => uncleared.deposits

          = render :partial => "statements/subtotal", :object => statement.account_items.deposits.sum(&:amount)

      - if uncleared.checks.any?
        %fieldset#checks
          %legend Checks

          .uncleared.checks
            %table= render :partial => "statements/uncleared", :collection => uncleared.checks

          = render :partial => "statements/subtotal", :object => statement.account_items.checks.sum(&:amount)

      - if uncleared.expenses.any?
        %fieldset#expenses
          %legend Other expenses

          .uncleared.expenses
            %table= render :partial => "statements/uncleared", :collection => uncleared.expenses

          = render :partial => "statements/subtotal", :object => statement.account_items.expenses.sum(&:amount)

      #balanced{:style => visible?(statement.balanced?)}
        %h3 Congratulations!

        %p Your records exactly match your account statement, and everything balances.

        %p= form.submit "Close out this statement"

      %p#actions{:style => visible?(!statement.balanced?)}
        = form.submit "Save for later"
        or
        = link_to("abort this reconciliation", statement_path(statement), :method => :delete, :confirm => "Are you sure you want to discard this reconciliation?")

app/views/statements/index.html.haml
#data.content
  .navigation
    = link_to "Dashboard", subscription_path(subscription)
    = link_to h(account.name), account_path(account)

  %h2 Previous Statements

  - if statements.empty?
    %p== You have not yet balanced this account against any statements from your financial institution. You may start by clicking #{link_to("here", new_account_statement_path(account))}, to begin balancing this account.

  - else
    %ul
      - statements.each do |statement|
        %li
          = link_to(statement.occurred_on.strftime("%Y-%m-%d"), statement_path(statement))
          = ":"
          = format_cents(statement.ending_balance)

app/views/statements/new.html.haml
#data.content
  %h2== Let's reconcile your #{h(account.name)} account

  .form

    = form_for([account, statement]) do |form|

      %fieldset

        %p First, take a look at the account statement from your bank or other financial institution.

        %p If you haven't reconciled in a while, make sure you start with the <em>oldest</em> statement and work forward.
        
        %p
          <strong>When</strong> was the statement printed?
          = form.date_select :occurred_on, :size => 10
        
        %p
          <strong>What</strong> is the ending balance?
          = "$"
          = form.text_field(:ending_balance, :size => 8, :class => "number", :value => format_cents(statement.ending_balance, :unit => ""), :onchange => "this.value = Money.format(this)")

      %p
        = form.submit "Go to step #2"
        or
        = link_to("cancel", account_path(account))

app/views/statements/show.html.haml
#data.content
  .navigation
    = link_to "Dashboard", subscription_path(subscription)
    = link_to h(account.name), account_path(account)
    = link_to "Prior statements", account_statements_path(account)

  %h2
    %span.actions
      = link_to("Delete", statement_path(statement), :confirm => "Are you sure you want to delete this statement?", :method => :delete)
    Statement for period ending
    = statement.occurred_on.strftime("%Y-%m-%d")

  %table.entries
    = render :partial => "events/balance", :locals => { :container => statement }
    = render(statement.account_items)