config/routes.rb
Rails.application.routes.draw do
  resource :session do
    get :logout, on: :member
  end

  resources :events do
    get :show, on: :member
    post :update, on: :member
  end

  resources :subscriptions do
    resources :events, shallow: true do
      resources :tagged_items
    end
    resources :accounts, shallow: true do
      resources :buckets, shallow: true do
        resources :events
      end
      resources :events
      resources :statements
    end
    resources :tags, shallow: true do
      resources :events
    end
  end



  root to: 'subscriptions#index'
  # map.with_options :controller => "subscriptions", :action => "index" do |home|
  #   home.root
  #   home.connect ""
  # end
end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  RECENT_WINDOW_SIZE = 10

  Temp = Struct.new(:id, :name, :role, :balance)

  belongs_to :account
  belongs_to :author, :class_name => "User", :foreign_key => "user_id"

  has_many :line_items

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :account_id, :case_sensitive => false

  scope :apply_filter, ->(filter) do
    conditions = []
    parameters = []

    if filter.from?
      conditions << "line_items.occurred_on >= ?"
      parameters << filter.from
    end

    if filter.to?
      conditions << "line_items.occurred_on <= ?"
      parameters << filter.to
    end

    if filter.by_type?
      roles = []

      if filter.expenses?
        roles << 'payment_source'
        roles << 'transfer_from'
        roles << 'credit_options'
      end

      if filter.deposits?
        roles << 'deposit'
        roles << 'transfer_to'
      end

      if filter.reallocations?
        roles << 'primary'
        roles << 'aside'
        roles << 'credit_options'
        roles << 'reallocation_from'
        roles << 'reallocation_to'
      end

      conditions << "line_items.role IN (?)"
      parameters << roles.uniq
    end

    joins("LEFT OUTER JOIN line_items ON line_items.bucket_id = buckets.id")
      .select("buckets.*, SUM(line_items.amount) as computed_balance")
      .where([conditions.join(" AND "), *parameters])
      .group("buckets.id")
  end

  def self.default
    Temp.new("r:default", "General", "default", 0)
  end

  def self.aside
    Temp.new("r:aside", "Aside", "aside", 0)
  end

  def self.template
    new :name => "Bucket name (e.g. Groceries)",
      :role => "aside | default | nil"
  end

  def self.recent(n=RECENT_WINDOW_SIZE)
    limit(n).order("updated_at DESC").sort_by(&:name)
  end

  def balance
    (self[:computed_balance] || self[:balance]).to_i
  end

  def assimilate(bucket)
    if bucket == self
      raise ArgumentError, "cannot assimilate self"
    end

    if bucket.account_id != account_id
      raise ArgumentError, "cannot assimilate bucket from different account"
    end

    old_id = bucket.id

    Bucket.transaction do
      LineItem.where(:bucket_id => old_id).update_all(["bucket_id = ?", id])
      update_attribute :balance, balance + bucket.balance
      bucket.destroy
    end
  end

  def to_xml(options={})
    options[:only] = %w(name role) if new_record?
    JSON.parse(to_json).to_xml(options.merge(root: 'bucket'))
  end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  # acceptable_includes :author

  before_action :find_account, :only => %w(index new create)
  before_action :find_bucket, :except => %w(index new create)

  def index
    @filter = QueryFilter.new(params)
    if @filter.any?
      @buckets = account.buckets.apply_filter(@filter)
    else
      @buckets = account.buckets
    end

    respond_to do |format|
      format.html
      format.xml { render :xml => @buckets.to_xml(eager_options(:root => "buckets")) }
    end
  end

  def show
    respond_to do |format|
      format.html do
        @page = (params[:page] || 0).to_i
        @more_pages, @items = bucket.line_items.page(@page)
      end

      format.xml { render :xml => bucket.to_xml(eager_options) }
    end
  end

  def new
    respond_to { |format| format.xml { render :xml => Bucket.template.to_xml } }
  end

  def create
    respond_to do |format|
      format.xml do
        @bucket = account.buckets.where(:author => user).create!(bucket_params)
        render :status => :created, :xml => @bucket.to_xml, :location => bucket_url(@bucket)
      end
    end
  rescue ActiveRecord::RecordInvalid => error
    @bucket = error.record
    respond_to do |format|
      format.xml { render :status => :unprocessable_entity, :xml => @bucket.errors.to_xml }
    end
  end

  def update
    bucket.update!(bucket_params)

    respond_to do |format|
      format.js
      format.xml { render :xml => bucket.to_xml }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.js
      format.xml { render :status => :unprocessable_entity, :xml => bucket.errors.to_xml }
    end
  end

  def destroy
    receiver = account.buckets.find(params[:receiver_id])
    receiver.assimilate(bucket)

    respond_to do |format|
      format.html { redirect_to(receiver) }
      format.xml  { head :ok }
    end
  end

  protected

  attr_reader :account, :bucket, :buckets, :filter
  helper_method :account, :bucket, :buckets, :filter

  def find_account
    @account = Account.find(params[:account_id])
    @subscription = user.subscriptions.find(@account.subscription_id)
  end

  def find_bucket
    @bucket = Bucket.find(params[:id])
    @account = @bucket.account
    @subscription = user.subscriptions.find(@account.subscription_id)
  end

  def current_location
    if bucket
      "buckets/%d" % bucket.id
    else
      super
    end
  end

  def bucket_params
    params.require(:bucket)
          .permit(:name, :role)
  end
end

app/helpers/buckets_helper.rb
module BucketsHelper
  def source_view
    params[:view] || "index"
  end

  def possible_receiver_buckets
    (account.buckets - [bucket]).sort_by(&:name)
  end
end

app/views/buckets/_bucket.html.haml
%tr.bucket{:id => dom_id(bucket), :class => cycle('odd', 'even'), :onmouseover => "Buckets.onMouseOver(#{bucket.id})", :onmouseout => "Buckets.onMouseOut(#{bucket.id})"}

  %td{:id => dom_id(bucket, :name)}
    = render :partial => "buckets/bucket_name_for_index", :locals => { :bucket => bucket }

  = balance_cell(bucket)

app/views/buckets/_bucket_name.html.haml
.nubbin{:id => dom_id(bucket, :nubbin), :style => "display: none"}
  = link_to_function("&#x2913;", "Buckets.transferTo(#{bucket.account_id}, #{bucket.id})", :class => "button")
  = link_to_function("&#x21A5;", "Buckets.transferFrom(#{bucket.account_id}, #{bucket.id})", :class => "button")
  = link_to_function("&#x270e;", "Buckets.rename(#{bucket_path(bucket).to_json}, #{bucket.name.to_json}, #{form_authenticity_token.to_json})", :class => "button")
= link_to(h(bucket.name), bucket, :class => "bucket")

app/views/buckets/_bucket_name_for_index.html.haml
.nubbin{:id => dom_id(bucket, :nubbin), :style => "display: none"}
  = link_to("+", "#", onclick: "Buckets.transferTo(#{bucket.account_id}, #{bucket.id})", :class => "button")
  = link_to("-", "#", onclick: "Buckets.transferFrom(#{bucket.account_id}, #{bucket.id})", :class => "button")
  = link_to("&#x270e;".html_safe, "#", onclick: "Buckets.rename(#{bucket_path(bucket).to_json}, #{bucket.name.to_json}, #{form_authenticity_token.to_json})", :class => "button")
= link_to(h(bucket.name), bucket, :class => "bucket")

app/views/buckets/_bucket_name_for_perma.html.haml
%span.actions== #{link_to("Rename", "#", onclick: "Buckets.rename(#{bucket_path(bucket).to_json}, #{bucket.name.to_json}, #{form_authenticity_token.to_json})")} | #{link_to("Delete/Merge", "#", onclick: "Buckets.deleteBucket()")}
== #{link_to(h(bucket.account.name), bucket.account)}:
&= bucket.name

app/views/buckets/_delete_form.html.haml
- form_tag(bucket_path(bucket), :method => 'delete', :onsubmit => "return Buckets.confirmDelete()") do
  %fieldset
    %legend Delete/Merge
    %p== To delete this bucket, you'll need to move the transactions from "#{h(bucket.name)}" into another bucket.
    %p
      Please select that other bucket:
      = select_tag(:receiver_id, options_from_collection_for_select(possible_receiver_buckets, :id, :name, account.buckets.default.id))
  %p
    = submit_tag "Merge and delete this bucket"
    == or #{link_to("Cancel", "#", onclick: "Buckets.cancelDelete()")}

app/views/buckets/index.html.haml
:javascript
  Buckets.newEventUrl = #{new_subscription_event_path(subscription).to_json}

#data.content
  .navigation
    = link_to "Dashboard", subscription_path(subscription)
    = link_to "Transactions in #{h(account.name)}", account_path(account)

  %h2
    = balance_cell(account, :classes => %w(total balance), :tag => "span")
    == Buckets in #{h(account.name)}

  = link_to(filter, '#', onclick: "Filters.display()", :id => :filter_nubbin)

  #filter_form{:style => "display: none"}
    - form_tag(account_buckets_path(account), :method => :get) do
      %p
        Include:
        %label
          = check_box_tag(:expenses, "1", filter.expenses?)
          Expenses
        = "|"
        %label
          = check_box_tag(:deposits, "1", filter.deposits?)
          Deposits
        = "|"
        %label
          = check_box_tag(:reallocations, "1", filter.reallocations?)
          Reallocations
      %p
        %label
          From:
          = date_field_tag :from, filter.from, :size => 9
        %label
          To:
          = date_field_tag :to, filter.to, :size => 9

      %p.actions
        = submit_tag "Apply these criteria", :name => nil
        or
        = link_to "cancel", "#", onclick: "Filters.hide()"
        - if filter.any?
          or
          = link_to("reset this filter", account_buckets_path(account))

  %table#accounts_summary
    = render(buckets.sort_by(&:name))

app/views/buckets/show.html.haml
#delete_form.form{:style => "display: none;"}= render :partial => "buckets/delete_form"

#data.content
  .navigation
    = link_to "Dashboard", subscription_path(subscription)
    = link_to "Transactions in #{h(account.name)}", account_path(account)
    = link_to "Buckets in #{h(account.name)}", account_buckets_path(account)

  %h2{:id => dom_id(bucket, :name)}
    = render :partial => "buckets/bucket_name_for_perma", :locals => { :bucket => bucket }

  %table.entries
    = render :partial => "events/balance", :locals => { :container => bucket }
    = render(@items)

app/views/buckets/update.js.erb
<% update_page do |page|
  if bucket.valid?
    page[dom_id(bucket, :name)].replace_html :partial => "buckets/bucket_name_for_#{source_view}",
      :locals => { :bucket => bucket }
  else
    errors = bucket.errors.full_messages.join("\n")
    page.alert("The bucket could not be updated:\n\n" + errors);
  end
end %>