config/routes.rb
Rails.application.routes.draw do
  resource :session do
    get :logout, on: :member
  end

  resources :events do
    get :show, on: :member
    post :update, on: :member
  end

  resources :subscriptions do
    resources :events, shallow: true do
      resources :tagged_items
    end
    resources :accounts, shallow: true do
      resources :buckets, shallow: true do
        resources :events
      end
      resources :events
      resources :statements
    end
    resources :tags, shallow: true do
      resources :events
    end
  end



  root to: 'subscriptions#index'
  # map.with_options :controller => "subscriptions", :action => "index" do |home|
  #   home.root
  #   home.connect ""
  # end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :subscription

  has_many :tagged_items, :dependent => :delete_all

  # attr_accessible :name

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :subscription_id, :case_sensitive => false

  def self.template
    new :name => "name of tag"
  end

  def assimilate(tag)
    raise ActiveRecord::RecordNotSaved, "cannot assimilate self" if tag == self

    transaction do
      ActiveRecord::Base.connection.update <<-SQL.squish
        UPDATE tagged_items
           SET tag_id = #{id}
         WHERE tag_id = #{tag.id}
      SQL
      tag.tagged_items.reset

      update_attribute :balance, balance + tag.balance
      tag.destroy
    end
  end

  def to_xml(options={})
    options[:only] = Array(options[:only]) + [:name] if new_record?
    JSON.parse(to_json(options)).to_xml(root: 'tag')
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_subscription, :only => %w(index new create)
  before_action :find_tag, :except => %w(index new create)

  def index
    respond_to do |format|
      format.xml { render :xml => subscription.tags.to_xml(:root => "tags") }
    end
  end

  def show
    respond_to do |format|
      format.html do
        @page = (params[:page] || 0).to_i
        @more_pages, @items = tag_ref.tagged_items.page(@page)
      end
      format.xml { render :xml => tag_ref }
    end
  end

  def new
    respond_to { |format| format.xml { render :xml => Tag.template } }
  end

  def create
    respond_to do |format|
      format.xml do
        @tag_ref = subscription.tags.create!(tags_params)
        render :xml => @tag_ref, :status => :created, :location => tag_url(@tag_ref)
      end
    end
  rescue ActiveRecord::RecordInvalid => error
    respond_to do |format|
      format.xml { render :status => :unprocessable_entity, :xml => error.record.errors }
    end
  end

  def update
    tag_ref.update!(tags_params)
    respond_to do |format|
      format.js
      format.xml { render :xml => tag_ref }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.js
      format.xml { render :status => :unprocessable_entity, :xml => tag_ref.errors }
    end
  end

  def destroy
    if params[:receiver_id].present?
      receiver = subscription.tags.find(params[:receiver_id])
      receiver.assimilate(tag_ref)
    else
      tag_ref.destroy
    end

    respond_to do |format|
      format.html { redirect_to(receiver || subscription) }
      format.xml { head :ok }
    end
  rescue ActiveRecord::RecordNotSaved => error
    head :unprocessable_entity
  end

  protected

  # can't call it 'tag' because that conflicts with the Rails 'tag()'
  # helper method. 'tag_ref' is lame, but sufficient.
  attr_reader :tag_ref
  helper_method :tag_ref

  def find_tag
    @tag_ref = Tag.find(params[:id])
    @subscription = user.subscriptions.find(@tag_ref.subscription_id)
  end

  def current_location
    if tag_ref
      "tags/%d" % tag_ref.id
    else
      super
    end
  end

  def tags_params
    params.require(:tag).permit(:name, :balance)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def possible_receiver_tags
    @possible_receiver_tags ||= (subscription.tags - [tag_ref]).sort_by(&:name)
  end
end

app/views/tags/_cloud.html.haml
#cloud
  - subscription.tags.sort_by(&:name).each do |item|
    = link_to(item.name, tag_path(item))

app/views/tags/_delete_form.html.haml
- form_tag(tag_path(tag_ref), :method => 'delete', :onsubmit => "return Tags.confirmDelete()") do
  - if possible_receiver_tags.any?
    %fieldset
      %legend Delete/Merge

      %label#deleteTagOption.option.selected
        = radio_button_tag(:merge, 'no', true, :onclick => "Tags.selectDeleteTag()")
        == Delete the "#{h tag_ref.name}" tag

      %label#mergeTagOption.option
        = radio_button_tag(:merge, 'yes', false, :onclick => "Tags.selectMergeTag()")
        == Merge the "#{h tag_ref.name}" tag into
        = select_tag(:receiver_id, "<option></option>" + options_from_collection_for_select(possible_receiver_tags, :id, :name))

    %p
      = submit_tag "Delete this tag"
      or
      = link_to("Cancel", "#", onclick: "Tags.cancelDelete()")

app/views/tags/_name.html.haml
%span.actions== #{link_to("Rename", "#", onclick: "Tags.rename(#{tag_path(tag_ref).to_json}, #{tag_ref.name.to_json}, #{form_authenticity_token.to_json})")} | #{link_to("Delete", "#", onclick: "Tags.deleteTag()")}
== Transactions tagged "#{h(tag_ref.name)}"

app/views/tags/show.html.haml
#delete_form.form{:style => "display: none;"}= render :partial => "tags/delete_form"

#data.content
  .navigation
    = link_to "Dashboard", subscription_path(subscription)

  %h2#name= render :partial => "tags/name"

  %table.entries
    = render :partial => "events/balance", :locals => { :container => tag_ref }
    = render(@items)

app/views/tags/update.js.erb
<%= update_page do |page|
  page[:name].replace_html :partial => "tags/name"
end %>