config/routes.rb
Rails.application.routes.draw do
  resource :session do
    get :logout, on: :member
  end

  resources :events do
    get :show, on: :member
    post :update, on: :member
  end

  resources :subscriptions do
    resources :events, shallow: true do
      resources :tagged_items
    end
    resources :accounts, shallow: true do
      resources :buckets, shallow: true do
        resources :events
      end
      resources :events
      resources :statements
    end
    resources :tags, shallow: true do
      resources :events
    end
  end



  root to: 'subscriptions#index'
  # map.with_options :controller => "subscriptions", :action => "index" do |home|
  #   home.root
  #   home.connect ""
  # end
end

app/models/account.rb
class Account < ActiveRecord::Base
  DEFAULT_BUCKET_NAME = "General"

  # When should the levels of credit cards be reached (in %)
  DEFAULT_LIMIT_VALUES = {
    :critical => 100,
    :high => 80,
    :medium => 30,
    :low => 0
  }

  belongs_to :subscription
  belongs_to :author, :class_name => "User", :foreign_key => "user_id"

  attr_accessor :starting_balance
  # attr_accessible :name, :role, :limit, :starting_balance

  validates_presence_of :name
  validates_presence_of :limit, :if => :credit_card?
  validates_uniqueness_of :name, :scope => :subscription_id, :case_sensitive => false

  has_many :buckets do
    def for_role(role, user)
      role = role.downcase
      find_by_role(role) || where(:author => user).create({:name => role.capitalize, :role => role})
    end

    def sorted
      sort_by(&:name)
    end

    def default
      detect { |bucket| bucket.role == "default" }
    end

    def with_defaults
      buckets = to_a.dup
      buckets << Bucket.default unless buckets.any? { |bucket| bucket.role == "default" }
      buckets << Bucket.aside unless buckets.any? { |bucket| bucket.role == "aside" }
      return buckets
    end
  end

  has_many :line_items
  has_many :statements

  has_many :account_items, :extend => CategorizedItems

  after_create :create_default_buckets, :set_starting_balance

  def self.template
    new :name => "Account name (e.g. Checking)", :role => "checking | credit-card | nil",
      :starting_balance => { :amount => 0, :occurred_on => Date.today }
  end

  def credit_card?
    role == 'credit-card'
  end

  def checking?
    role == 'checking'
  end

  def available_balance
    @available_balance ||= balance - unavailable_balance
  end

  def unavailable_balance
    @unavailable_balance ||= begin
      aside = buckets.detect { |bucket| bucket.role == 'aside' }
      aside && aside.balance > 0 ? aside.balance : 0
    end
  end

  def destroy
    transaction do
      cleanup_account_items
      cleanup_line_items
      cleanup_buckets
      cleanup_tagged_items
      cleanup_events

      Account.delete(id)
    end
  end

  def to_xml(options={})
    if new_record?
      options[:only] = %w(name role)
      options[:procs] = Proc.new do |opts|
        starting_balance.to_xml(opts.merge(:root => "starting-balance"))
      end
    end

    JSON.parse(to_json).to_xml(options.merge(root: 'account'))
  end

  protected

    def create_default_buckets
      buckets.where(author: author).create({:name => DEFAULT_BUCKET_NAME, :role => "default"})
    end

    def set_starting_balance
      if starting_balance && !starting_balance[:amount].to_i.zero?
        amount = starting_balance[:amount].to_i
        role = amount > 0 ? "deposit" : "payment_source"
        subscription.events.where(user: author).create!({:occurred_on => starting_balance[:occurred_on],
            :actor_name => "Starting balance",
            :line_items => [{:account_id => id, :bucket_id => buckets.default.id,
              :amount => amount, :role => role}]
          })
        reload # make sure the balance is set correctly
      end
    end

  private

    def cleanup_line_items
      LineItem.where(account_id: id).delete_all
    end

    def cleanup_account_items
      items = account_items.includes(:event => [:line_items, :account_items])
                # .find(:all, :include => { :event => [:line_items, :account_items] })

      items.each do |item|
        event = item.event
        next unless event.account_items.length > 1

        case event.role
        when :transfer then
          # if half of a transfer is being deleted, convert the other half to either a deposit
          # or an expense, depending on whether the half being deleted is the negative or
          # positive half.
          event.line_items.update_all(:role => (item.amount < 0 ? 'deposit' : 'payment_source'))

        when :expense then
          # if the credit_options account is being deleted, we don't need to do anything,
          # but if the payment_source account is being deleted, then we need to convert the
          # credit_options items to a bucket reallocation.
          if event.account_for(:payment_source) == self
            event.line_items.where(role: 'aside').update_all({:role => 'primary'})
            event.line_items.where(role: 'credit_options').update_all({:role => 'reallocate_to'})
          end
        end
      end

      AccountItem.where(account_id: id).delete_all
    end

    def cleanup_buckets
      Bucket.where(account_id: id).delete_all
    end

    def cleanup_tagged_items
      tagged_items = TaggedItem.find_by_sql(<<-SQL.squish)
        SELECT t.* FROM tagged_items t LEFT JOIN events e ON t.event_id = e.id
         WHERE e.subscription_id = #{subscription_id}
           AND NOT EXISTS (
            SELECT * FROM account_items a WHERE a.event_id = e.id)
      SQL

      tagged_items.each { |item| item.destroy }
    end

    def cleanup_events
      ActiveRecord::Base.connection.delete(<<-SQL.squish)
        DELETE FROM events
         WHERE subscription_id = #{subscription_id}
           AND NOT EXISTS (
            SELECT * FROM account_items a WHERE a.event_id = events.id)
      SQL
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # acceptable_includes :author, :buckets

  before_action :find_account, :except => %w(index create new)
  before_action :find_subscription, :only => %w(index create new)

  def index
    respond_to do |format|
      format.xml { render :xml => subscription.accounts.to_xml(eager_options(:root => "accounts")) }
    end
  end

  def show
    respond_to do |format|
      format.html do
        @page = (params[:page] || 0).to_i
        @more_pages, @items = account.account_items.page(@page)
      end

      format.xml { render :xml => account.to_xml(eager_options) }
    end
  end

  def new
    respond_to do |format|
      format.html
      format.xml { render :xml => Account.template.to_xml }
    end
  end

  def create
    @account = subscription.accounts.where(author: user).create(account_params)
    if @account.errors.empty?
      respond_to do |format|
        format.html { redirect_to(subscription_url(subscription)) }
        format.xml  { render :xml => @account.to_xml, :status => :created, :location => account_url(@account) }
      end
    else
      respond_to do |format|
        format.html { render :action => "new" }
        format.xml  { render :status => :unprocessable_entity, :xml => @account.errors.to_xml }
      end
    end
  end

  def destroy
    account.destroy
    respond_to do |format|
      format.html { redirect_to(subscription_url(subscription)) }
      format.xml  { head :ok }
    end
  end

  def update
    account.update!(account_params)

    respond_to do |format|
      format.js
      format.xml { render :xml => account.to_xml }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.js
      format.xml { render :status => :unprocessable_entity, :xml => account.errors.to_xml }
    end
  end

  protected

  attr_reader :account
  helper_method :account

  def find_account
    @account = Account.find(params[:id])
    @subscription = user.subscriptions.find(@account.subscription_id)
  end

  def current_location
    if account && !account.new_record?
      "accounts/%d" % account.id
    else
      super
    end
  end

  def account_params
    params.require(:account)
          .permit(:name, :role, :limit, :current_balance, :subscription_id,
                  starting_balance: [ :amount, :occurred_on ] )
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def account_starting_balance_amount
    if @account && @account.starting_balance
      amount = @account.starting_balance[:amount].to_i
      "%.2f" % (amount / 100.0) unless amount.zero?
    end
  end

  def account_starting_balance_occurred_on
    @account.starting_balance[:occurred_on].to_date rescue Date.today
  end
end

app/views/accounts/_account.html.haml
%tr.account{:id => dom_id(account)}
  %th= link_to(account.name, account)
  = balance_cell(account, :classes => "total")
- if account.buckets.length > 1
  - reset_cycle
  = render(account.buckets.recent)
  - if account.buckets.length > Bucket::RECENT_WINDOW_SIZE
    %tr.bucket
      %td.more{:colspan => 2}
        &rarr;
        = link_to "See all #{account.buckets.length} buckets", account_buckets_path(account)

app/views/accounts/_form.html.haml
= form_for(@account || Account.new, :url => subscription_accounts_path(subscription), :html => { :onsubmit => "if(!Accounts.submit()) return false", :id => "new_account_form" }) do |form|
  - if form.object && !form.object.errors.empty?
    %fieldset.errors
      %legend Errors

      %p The account could not be saved because of the following error(s):
      %ul
        - form.object.errors.full_messages.each do |message|
          %li
            = message

  %fieldset
    %legend Account info

    %p
      %label{:for => "account_name"} <strong>Choose a name</strong> for this account:
      = form.text_field :name, :class => "text"

    %p
      %label
        <strong>What kind</strong> of account is this?
        = form.select :role, [["Checking", "checking"], ["Credit card", "credit-card"], ["Other", "other"]], {}, :onchange => "Accounts.showOrHideCreditLimit(this.value);"

    %p{:style => 'display: none;', :id => 'credit_limit_div'}
      %label
        What is the <strong>credit limit</strong>:
        == $#{form.text_field :limit, :class => "number", :size => 8}

  - if form.object.nil? || form.object.new_record?
    %fieldset
      %legend Starting balance

      .instructions
        %p <b>Take a look at your latest statement for this account.</b>
        %p Note the <em>current balance</em> from the statement, as |
          well as the <em>date the statement was issued</em>, and enter |
          them below. |
      = hidden_field_tag "account[starting_balance][amount]", ""

      %p
        %label
          What is the <strong>current balance</strong>:
          == $#{text_field_tag :current_balance, account_starting_balance_amount, :class => "number", :size => 8}

      %p
        %label
          <strong>When</strong> was the statement issued:
          = date_field_tag "account[starting_balance][occurred_on]", account_starting_balance_occurred_on, :size => 9

  %p
    = submit_tag "Create this account"
    or
    = link_to "cancel", "#", onclick: "Accounts.hideForm()"

app/views/accounts/_name.html.haml
%span.actions
  - if account.credit_card?
    = link_to("Adjust Limit", "#", onclick: "Accounts.adjustLimit(#{account_path(account).to_json}, #{account.limit.to_json}, #{form_authenticity_token.to_json})")
  |
  - if account.statements.pending.any?
    = link_to("Resume reconciling", edit_statement_path(account.statements.pending.first))
  - else
    = link_to("Reconcile", new_account_statement_path(account))
  |
  - if account.statements.balanced.any?
    = link_to("Prior statements", account_statements_path(account))
    |
  = link_to("Rename", "#", onclick: "Accounts.rename(#{account_path(account).to_json}, #{account.name.to_json}, #{form_authenticity_token.to_json})")
  |
  = link_to("Delete", account_path(account), :method => :delete, :confirm => "Are you sure you want to delete this account?")
&= account.name

app/views/accounts/new.html.haml
:javascript
  Accounts.origin = #{subscription_url(subscription).to_json};

#new_account.form= render :partial => "accounts/form"

app/views/accounts/show.html.haml
#data.content
  .navigation
    = link_to "Dashboard", subscription_path(subscription)
    = link_to "Buckets in #{h(account.name)}", account_buckets_path(account), :id => dom_id(account, :buckets)

  %h2{:id => dom_id(account, :name)}= render :partial => "accounts/name"

  %table.entries
    = render :partial => "events/balance", :locals => { :container => account }
    = render(@items)

app/views/accounts/update.js.erb
<%= update_page do |page|
  if account.valid?
    page[dom_id(account, :name)].replace_html :partial => "accounts/name",
      :locals => { :account => account }
    page[dom_id(account, :buckets)].replace_html("Buckets in #{h(account.name)}")
  else
    errors = account.errors.full_messages.join("\n")
    page.alert("The account could not be updated:\n\n" + errors)
  end
end %>